Installing Keras 

In [0]:
# https://keras.io/
!pip install -q keras #installing Keras package through pip
import keras #importing keras

Importing all the required packages

In [0]:
import numpy as np  #importing numpy

from keras.models import Sequential      #importing sequential from keras
from keras.layers import Flatten         #importing the package flatten
from keras.layers import Convolution2D   #importing Convolution2D for performing convolutions
from keras.utils import np_utils         #importing np_utils

from keras.datasets import mnist         #importing the dataset MNIST

spliting the data into train set and test set

In [0]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()     #downloading data from MNIST and loading it into train and test sets of input and output

plotting the image of a digit

In [8]:
print (X_train.shape)                         #displaying the shape of the input data. MNIST containg 60000 images of size 28 * 28      
from matplotlib import pyplot as plt          #importing pyplot in order to visualise the data  
%matplotlib inline                            #importing matplotlib inline 
plt.imshow(X_train[0])                        #plotting image by applying the image plotting function of matplotlib

(60000, 28, 28)


UsageError: unrecognized arguments: #importing matplotlib inline


In [0]:
X_train = X_train.reshape(X_train.shape[0], 28, 28,1)         
X_test = X_test.reshape(X_test.shape[0], 28, 28,1)

In [0]:
One - Hot Encoding

In [0]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255                                     #one hot encoding operation being performed

In [11]:
y_train[:10]    #shows the 10 digits of y_train[]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [0]:
# Convert 1-dimensional class arrays to 10-dimensional class matrices
Y_train = np_utils.to_categorical(y_train, 10)
Y_test = np_utils.to_categorical(y_test, 10)

In [13]:
Y_train[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

Convlution Layers

In [14]:
from keras.layers import Activation, MaxPooling2D                                    #importing Activation and Maxpooling2D to define the activation function and performing Maxpooling

model = Sequential()                                                                 #Sequential () being called on the model 
model.add(Convolution2D(32, 3, 3, activation='relu', input_shape=(28,28,1)))  # 28*28*1 | 3*3*32 = 26*26*32       #convolution operation being performed on Layer 1
model.add(Convolution2D(64, 3, 3, activation='relu'))                         # 26*26*32 | 3*3*64 = 24*24*64
model.add(Convolution2D(128, 3, 3, activation='relu'))                        # 24*24*64 | 3*3*128 = 22*22*128

model.add(MaxPooling2D(pool_size=(2, 2)))                                     # 22*22*128 | maxpool(2*2) = 11*11*128 #max pooling being performed with the maxpool size as 2 * 2

model.add(Convolution2D(256, 3, 3, activation='relu'))                        # 11*11*128  | 3*3*256 = 9*9*256    #convolution being performed on the subsequent layers with relu non linearity
model.add(Convolution2D(512, 3, 3, activation='relu'))                        # 9*9*256 | 3*3*512 = 7*7*512 
model.add(Convolution2D(1024, 3, 3, activation='relu'))                       # 7*7*512 | 3*3*1024 = 5*5*1024
model.add(Convolution2D(2048, 3, 3, activation='relu'))                       # 5*5*1024 | 3*3*2048 = 3*3*2048
model.add(Convolution2D(10, 3, 3, activation='relu'))                         # 3*3*10

model.add(Flatten())                                                                # the model is flattened at the last step to get a vector
model.add(Activation('softmax'))                                                    #the vector is being passed onto the softmax layer to get a probability - like number

model.summary()                                                                     #all the operations taking place in the model is summarised and displayed

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 22, 22, 128)       73856     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 11, 11, 128)       0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 9, 9, 256)         295168    
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 7, 7, 512)         1180160   
_________________________________________________________________
conv

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu", input_shape=(28, 28, 1...)`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu")`
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), activation="relu")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), activation="relu")`
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), activation="relu")`
  # This is added back by InteractiveShellApp.init

Model configuration

In [0]:
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])                                              #model is configured for training

Model training on the train dataset

In [16]:
model.fit(X_train, Y_train, batch_size=32, nb_epoch=10, verbose=1)              #model is trained on the train dataset for 10 epochs and batch size 32

Instructions for updating:
Use tf.cast instead.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/10
60000/60000 [==============================] - 119s 2ms/step - loss: 2.3028 - acc: 0.0986
Epoch 2/10
60000/60000 [==============================] - 112s 2ms/step - loss: 2.3026 - acc: 0.0987
Epoch 3/10
60000/60000 [==============================] - 112s 2ms/step - loss: 2.3026 - acc: 0.0987
Epoch 4/10
60000/60000 [==============================] - 112s 2ms/step - loss: 2.3026 - acc: 0.0987
Epoch 5/10
60000/60000 [==============================] - 112s 2ms/step - loss: 2.3026 - acc: 0.0987
Epoch 6/10
60000/60000 [==============================] - 112s 2ms/step - loss: 2.3026 - acc: 0.0987
Epoch 7/10
60000/60000 [==============================] - 112s 2ms/step - loss: 2.3026 - acc: 0.0987
Epoch 8/10
60000/60000 [==============================] - 112s 2ms/step - loss: 2.3026 - acc: 0.0987
Epoch 9/10
60000/60000 [==============================] - 112s 2ms/step - loss: 2.3026 - acc: 0.0987
Epoch 10/10
60000/60000 [==============================] - 112s 2ms/step - loss: 2.3026 - a

Model Evaluation

In [0]:
score = model.evaluate(X_test, Y_test, verbose=0)                               #model is trained and evaluated on test dataset

In [18]:
print(score)                                                                    #evaludation score on the test dataset

[2.3025851249694824, 0.098]


In [0]:
y_pred = model.predict(X_test)                                                  #predicting is made on the test set

In [20]:
print(y_pred[:9])                                                               #printing the output of y_pred
print(y_test[:9])                                                               #printing the output of y_test

[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
[7 2 1 0 4 1 4 9 5]


The reason why it is a bad model is because the loss is very and the model suffers from a lot of overfitting.
This is because of the several convolution operations that is being performed and also the hyperparameters are imitialized. 
